name: hexabyte
description: Application for using food waste as consumable organic resource.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0-69.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  google_fonts: ^2.3.1
  flutter_form_builder: ^7.1.1
  http: ^0.13.4
  auto_size_text: ^3.0.0
  flutter_secure_storage: ^5.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# auth, onboarding(if user not there), listing page(home), profile page, sellers page
# product details page, user orders page.

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
